### ISSUE TITLE
Python module?

### ISSUE THREAD

**Issue by dhhagan** [loftytopping/UManSysProp_public#1]
Is there a reason that this isn't formulated as a Python module? Do you mind if I fork it do so, so that it could be released as an actual python package? I think there are many of us (at least those of us here at MIT) that would prefer to use it as a package vs using the API.

**Comment by loftytopping** [comment]
Hi there! Sorry for the delay, I've just got back from paternity leave :). So it was released in the current format according to discussion we had during the publication of our academic paper and users within atmospheric chemistry. The current release of these predictive techniques in this repo will drop straight into the UManSysProp web framework, hosted at https://github.com/waveform80/umansysprop, to create the facility hosted at our website. Please do fork, and have fun! I'm always very interested to keep track of how these tools are being used so please do let me know. Thanks.

**Comment by loftytopping** [comment]
I have started removing confusing links to the UManSysProp client packages, aiming to leave this as a stand alone collection of property predictive techniques. I need to remove the dependency on the forms.py and renderers.py files. I will aim to do this before September.

**Comment by dhhagan** [comment]
Sounds great. There was also a bug somewhere that I patched...I'll have to check my commit log to see what it was. ha

**Comment by loftytopping** [comment]
Hi there. You should now be able to import this as a module. Thanks!
