### ISSUE TITLE
API POST??

### ISSUE THREAD

**Issue by dhhagan** [loftytopping/UManSysProp_public#2]
Is there a reason that requests are POST's rather than GET's??

**Comment by loftytopping** [comment]
If you would like anything changing on the server side, please let us know. I guess you guys are going to be sing this now as a standalone package rather than through the API

**Comment by dhhagan** [comment]
I'll probably use it as both, depending on what I'm doing. I was just looking at the API because otherwise I have to install babel with python bindings, which is a pain on non-windows machines.
