### ISSUE TITLE
Written in older version of Python?

### ISSUE THREAD

**Issue by aawiegel** [loftytopping/UManSysProp_public#3]
Thanks for providing the code for the property estimators!

Is this written in Python 2? I noticed that, for example, **init**.py contains the operator '<>', which has been depreciated. This throws a syntax error in Python 3.

**Comment by loftytopping** [comment]
Hi there! Sorry for the delay

Hmm thanks for noting this. Yes we did focus on Python 2 in the first instance, but I will spend some time sorting this out next week.

**Comment by aawiegel** [comment]
Thanks for your reply!

I tried working on it myself this weekend, but it would probably be more efficient this way since you are more familiar with the code. Being able to access the prediction methods directly through a python script would be really helpful for my current project, and of course we would cite this work in the final paper.

**Comment by loftytopping** [comment]
Hi! Ive removed the offending <> character so you 'should' be good to go. I hope this is the only problem. Given the package relies on Pybel, there might be more problems installing that in Python 3 than using this code. Let me know if there are other issues. Thanks!

**Comment by aawiegel** [comment]
Hello,

Thank you for looking into this. It works fine now as far as I can tell. Pybel also just came out with a new version in Python 3 last month, so that is not an issue.

**Comment by loftytopping** [comment]
Great! Enjoy and keep me posted on how it's benefitting your work :)
