### ISSUE TITLE
flask.ext now deprecated

### ISSUE THREAD

**Issue by dvalters** [loftytopping/UManSysProp_public#4]
[Issue arising from JOSS review of PyBox, which depend on UManSysProp (seemed more relevant to open the issue here)]

The API in newer versions of flask has changed, so `flask.ext` no longer works, e.g.

```ipython
<ipython-input-11-72b3b0cf0ac4> in <module>()
----> 1 from umansysprop.forms import CoreAbundanceField

~/Devel/UManSysProp_public/umansysprop/forms.py in <module>()
     41 
     42 import pybel
---> 43 from flask import request
     44 from flask.ext.wtf import Form as DeclarativeForm
     45 from wtforms.fields import (

ModuleNotFoundError: No module named 'flask'
```

See: https://stackoverflow.com/a/36733527/1953517 for solution

ref: https://github.com/openjournals/joss-reviews/issues/755

**Comment by loftytopping** [comment]
Thanks for this. Ive now updated the UManSysProp master branch to use flask_wtf inline with upto date Python3+.

**Comment by dvalters** [comment]
Great! Thanks :)
